.init_ssh: &init_ssh |
  mkdir -p ~/.ssh
  echo -e "$SSH_PRIVATE_KEY_TEST" > ~/.ssh/id_rsa
  chmod 600 ~/.ssh/id_rsa
  [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

stage-build-and-up:
  image: docker:dind
  script:
    # - sed -i s/api\.llamatech.top/$API_LOCATION/g .env.development
    - cat .env.development
    - docker build -t qpay-client .
    # - docker push registry.llamatech.top/runner-lab
    - *init_ssh
    - ssh $SSH_USER_TEST@$SERVER_TEST << EOF
    - cd $DOCKER_COMPOSE_DIRECTORY
    - docker-compose up -d $SERVICE_NAME
    - EOF
  only: 
    - /^dev$/

stage-build-demo-and-up:
  image: docker:dind
  script: 
    - cp .env.development.demo .env.development
    - cat .env.development
    - docker build -t qpay-client:demo .
    - *init_ssh
    - ssh $SSH_USER_TEST@$SERVER_TEST << EOF
    - cd $DEMO_DOCKER_COMPOSE_DIRECTORY
    - docker-compose up -d $SERVICE_NAME
    - EOF
  only: 
    - /^demo$/